# Generated by Django 4.2.5 on 2023-09-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finapp', '0003_asset_user_cashflow_user_liability_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='value',
            new_name='amount',
        ),
    ]
