# Generated by Django 4.2.5 on 2023-11-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finapp', '0005_riskprofile_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='risk_profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
