# Generated by Django 4.2.5 on 2023-11-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finapp', '0008_expense_name_income_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='discretionary_expenses',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='living_expenses',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
