# Generated by Django 4.2.5 on 2023-11-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finapp', '0009_remove_expense_discretionary_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
