# Generated by Django 4.2.5 on 2023-11-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finapp', '0010_expense_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='gross_income',
        ),
    ]
