# Generated by Django 4.2.5 on 2023-11-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finapp', '0011_remove_income_gross_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlow',
        ),
    ]
