# Generated by Django 4.2.5 on 2023-11-11 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Finapp', '0012_delete_cashflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='investment_experience',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='risk_profile',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='risk_tolerance',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='experience',
            field=models.CharField(choices=[('<1', 'Less than 1 year'), ('1-2', '1-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('10+', 'More than 10 years')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_1',
            field=models.CharField(choices=[('1', 'Strongly Disagree'), ('2', 'Disagree'), ('3', 'Neutral'), ('4', 'Agree'), ('5', 'Strongly Agree')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_2',
            field=models.CharField(choices=[('1', 'Strongly Disagree'), ('2', 'Disagree'), ('3', 'Neutral'), ('4', 'Agree'), ('5', 'Strongly Agree')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_3',
            field=models.CharField(choices=[('1', 'Strongly Disagree'), ('2', 'Disagree'), ('3', 'Neutral'), ('4', 'Agree'), ('5', 'Strongly Agree')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
