# Generated by Django 4.2.5 on 2023-11-12 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Finapp', '0013_remove_questionnaire_investment_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_3',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='investment_experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='risk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finapp.riskprofile'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='risk_tolerance',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
